name: bastion
description: "Bastion by No Bars Club"
publish_to: 'none'
version: 9.5.0+16

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^2.1.0
  flserial:
    git:
      url: https://github.com/MeshEnvy/flserial.git
      ref: 48216310061efc8d5d217cc18014fc2cb501646e
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_local_notifications: ^22.0.0
  crypto: ^3.0.3
  pointycastle: ^4.0.0
  http: ^1.2.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  flutter_foreground_task: ^9.2.0
  characters: ^1.4.0
  package_info_plus: ^10.1.0
  mobile_scanner: ^7.1.4
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.0
  flutter_linkify: ^6.0.0
  gpx: ^2.3.0
  path_provider: ^2.1.5
  share_plus: ^13.1.0
  build_pipe: ^0.3.1
  material_symbols_icons: ^4.2928.1
  web: ^1.1.1
  flutter_svg: ^2.0.10+1
  flutter_blue_plus_platform_interface: ^9.0.2
  ml_algo: ^16.0.0
  ml_dataframe: ^1.0.0
  llamadart: ^0.8.0
  flutter_langdetect: ^0.0.1
  cryptography: ^2.9.0
  cryptography_flutter: ^2.3.4
  convert: ^3.1.2
  flutter_onnxruntime: ^1.8.3

hooks:
  user_defines:
    llamadart:
      llamadart_native_backends:
        platforms:
          android-arm64:
            backends: [cpu]
          android-x64:
            backends: [cpu]

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
        - asset: assets/fonts/InterItalic.ttf
          style: italic
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "mesh-icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#111418"
  adaptive_icon_foreground: "mesh-icon.png"

build_pipe:
  workflows:
    default:
      clean_flutter: true
      generate_log: true
      platforms:
        web:
          build:
            build_command: flutter build web --release --pwa-strategy=none
            add_version_query_param: true
